# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/shiba/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),shiba)

$(call add-radio-file-sha1-checked,radio/abl.img,257140bdbd38621eb8902c62cb254e4899877e57)
$(call add-radio-file-sha1-checked,radio/bl1.img,51f0ab34bca330d3421847d161a3ff25402a36c9)
$(call add-radio-file-sha1-checked,radio/bl2.img,9623113a302c920a3c682f6b4ef10780764373fb)
$(call add-radio-file-sha1-checked,radio/bl31.img,b51c8881389bc774c596ca84322b5cf50a71f8b8)
$(call add-radio-file-sha1-checked,radio/gcf.img,7a1fb096a10a585463ab400b3376d76e5289c368)
$(call add-radio-file-sha1-checked,radio/gsa.img,420b346c3279ddf64908ef338996d1ad579560d1)
$(call add-radio-file-sha1-checked,radio/gsa_bl1.img,31fed1b543b0a4bf4c47f089cfb190f9fb6c751d)
$(call add-radio-file-sha1-checked,radio/ldfw.img,27867e9e3dca8a4503555ce74de26803c656f59a)
$(call add-radio-file-sha1-checked,radio/modem.img,4d26806d0d9899b0c1762dcd18ac97d3065c278b)
$(call add-radio-file-sha1-checked,radio/pbl.img,ae550eb2025666847b1bf3f4e3af3a764d8e7216)
$(call add-radio-file-sha1-checked,radio/tzsw.img,47c72e3dc41ad7e874a34d79b412c1073284e74b)

endif
